name: im_muslim
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2
environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  geolocator: ^14.0.2
  flutter_qiblah: ^3.2.0
  adhan: ^2.0.0+1
  google_fonts: ^8.0.2
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  geocoding: ^4.0.0
  quran_library:
    path: packages/quran_library_lite
  share_plus: ^12.0.1
  hijri: ^3.0.0
  flutter_local_notifications: ^21.0.0-dev.2
  flutter_timezone: ^5.0.1
  timezone: ^0.11.0
  hadith: 1.0.1
  http: ^1.2.2
  just_audio: ^0.10.5
  audioplayers: ^6.1.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  home_widget: ^0.9.0
  url_launcher: ^6.3.0
  video_player: ^2.10.0
  syncfusion_flutter_pdfviewer: ^32.2.5
  wakelock_plus: ^1.4.0
  flutter_islamic_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  file_picker: ^8.1.4
  pusher_channels_flutter: ^2.2.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/sounds/azan/
    - assets/branding/
    - .env
  fonts:
    - family: KFGQPC Uthmanic Script
      fonts:
        - asset: assets/fonts/KFGQPC_Uthmanic_Script.ttf
